# Generated by Django 5.2.1 on 2025-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0003_productlabel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_must_haves',
            field=models.BooleanField(default=False),
        ),
    ]
