# Generated by Django 5.2.1 on 2025-09-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_product_is_must_haves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_popular',
            new_name='come_in_minutes',
        ),
    ]
