# Generated by Django 5.2.1 on 2025-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0006_pharmacyservice_servicebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='mock_transaction_id',
        ),
        migrations.AddField(
            model_name='pharmacyservice',
            name='category',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('vaccination', 'Vaccination'), ('lab_test', 'Lab Test'), ('delivery', 'Delivery')], default='consultation', max_length=50),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='test_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
