# Generated by Django 5.2.1 on 2025-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_remove_servicebooking_mock_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='address',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='hospital_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='doctor_name',
            field=models.CharField(max_length=100),
        ),
    ]
