# Generated by Django 5.2.1 on 2025-10-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0013_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_options', to='Mainpage.product')),
            ],
        ),
    ]
