# Generated by Django 5.2.1 on 2025-10-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviewer_images/'),
        ),
    ]
