# Generated by Django 5.2.1 on 2025-11-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0021_articlecategory_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medicine_type',
            field=models.CharField(choices=[('LIQUID', 'Liquid'), ('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('CREAM', 'Cream'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
